### ISSUE TITLE
visualize() error

### ISSUE THREAD

**Issue by malmaud** [malmaud/TensorFlow.jl#381]
Reported by Alan Edelman:

```
visualize()
Traceback (most recent call last):
  File "/Users/alanedelman/.julia/v0.6/Conda/deps/usr/bin/tensorboard", line 4, in <module>
    import tensorflow.tensorboard.tensorboard
ImportError: No module named tensorboard.tensorboard
Traceback (most recent call last):
  File "/Users/alanedelman/.julia/v0.6/Conda/deps/usr/bin/tensorboard", line 4, in <module>
    import tensorflow.tensorboard.tensorboard
ImportError: No module named tensorboard.tensorboard
```

**Comment by oxinabox** [comment]
I believe this is because we don't automatically install tensorboard via Conda.
Maybe we should.

**Comment by oxinabox** [comment]
Fixed
